// The media library: directory-as-index listing, duration probing, and the
// add/delete operations the settings panel drives.
//
// Everything runs against a throwaway data root, so no test can touch a real
// user's library. The WAV fixture is generated byte by byte: a media file with
// a known, correct header is the only way to prove the duration arithmetic.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "zct-library-"));
process.env.ZCODE_TARKOV_DATA_DIR = root;

const { listTracks, enabledTracks, listPool, addMediaFile, deleteMediaFile, probeDuration, mediaFileExists } =
  await import("../.test-build/media/library.js");
const { mediaDir } = await import("../.test-build/core/dataRoot.js");
const { defaultPrefs } = await import("../.test-build/prefs/defaults.js");
const { MAX_UPLOAD_BYTES } = await import("../.test-build/media/stream.js");
const { UnsafePathError } = await import("../.test-build/media/paths.js");

function resetDir(kind) {
  fs.rmSync(mediaDir(kind), { recursive: true, force: true });
  fs.mkdirSync(mediaDir(kind), { recursive: true });
}

function put(kind, name, contents) {
  fs.mkdirSync(mediaDir(kind), { recursive: true });
  const file = path.join(mediaDir(kind), name);
  fs.writeFileSync(file, contents);
  return file;
}

/** A real RIFF/WAVE file with PCM fmt and a data chunk of the requested length. */
function wav(seconds, { sampleRate = 8000, channels = 1, bits = 16 } = {}) {
  const blockAlign = (channels * bits) / 8;
  const byteRate = sampleRate * blockAlign;
  const dataSize = Math.round(byteRate * seconds);
  const buf = Buffer.alloc(44 + dataSize);
  buf.write("RIFF", 0, "ascii");
  buf.writeUInt32LE(36 + dataSize, 4);
  buf.write("WAVE", 8, "ascii");
  buf.write("fmt ", 12, "ascii");
  buf.writeUInt32LE(16, 16);
  buf.writeUInt16LE(1, 20); // PCM
  buf.writeUInt16LE(channels, 22);
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(byteRate, 28);
  buf.writeUInt16LE(blockAlign, 32);
  buf.writeUInt16LE(bits, 34);
  buf.write("data", 36, "ascii");
  buf.writeUInt32LE(dataSize, 40);
  return buf;
}

// --- listing -----------------------------------------------------------------

test("listTracks reads music/ and reports what the dock needs", () => {
  resetDir("music");
  put("music", "a.mp3", "not really mpeg");
  put("music", "b.wav", wav(2.5));
  put("music", "notes.txt", "not audio");

  const tracks = listTracks(defaultPrefs());
  assert.deepEqual(
    tracks.map((t) => t.id),
    ["a.mp3", "b.wav"],
    "only servable audio is a track"
  );
  const [a, b] = tracks;
  assert.equal(a.displayName, "a", "the extension is not part of the label");
  assert.equal(a.enabled, true, "a fresh install has no opt-outs");
  assert.equal(a.size, "not really mpeg".length);
  assert.ok(a.mtimeMs > 0, "the panel orders tracks by modification time");
  assert.equal(a.durationSeconds, undefined, "an unreadable header reports no length rather than guessing");
  assert.ok(
    Math.abs(b.durationSeconds - 2.5) < 1e-6,
    `the RIFF byte rate and data size say 2.5 s, got ${b.durationSeconds}`
  );
});

test("disabledTracks turns a track off without touching the file", () => {
  resetDir("music");
  put("music", "a.mp3", "aa");
  put("music", "b.mp3", "bb");
  const prefs = defaultPrefs();
  prefs.audio.bgm.disabledTracks = ["b.mp3"];

  const tracks = listTracks(prefs);
  assert.equal(tracks.find((t) => t.id === "b.mp3").enabled, false, "the opt-out list is the only persisted state");
  assert.deepEqual(
    enabledTracks(prefs).map((t) => t.id),
    ["a.mp3"],
    "the dock only walks the enabled subset"
  );
  assert.equal(fs.existsSync(path.join(mediaDir("music"), "b.mp3")), true, "switching a track off is not a delete");
});

test("listPool reports each media kind with its sizes", () => {
  const files = { sounds: "ping.mp3", voice: "line.wav", pet: "pet.png", status: "texts.zh.txt" };
  for (const [kind, name] of Object.entries(files)) {
    resetDir(kind);
    put(kind, name, "data");
  }
  for (const [kind, name] of Object.entries(files)) {
    const entries = listPool(kind);
    assert.deepEqual(
      entries.map((e) => e.id),
      [name],
      `${kind}/ holds exactly what was written`
    );
    assert.equal(entries[0].size, 4);
  }
});

// --- duration probing --------------------------------------------------------

test("probeDuration computes seconds from a generated RIFF/WAVE header", () => {
  const file = put("music", "exact.wav", wav(2.5));
  const seconds = probeDuration(file, fs.statSync(file).size);
  assert.ok(Math.abs(seconds - 2.5) < 1e-6, `16000 bytes/s over 40000 data bytes is 2.5 s, got ${seconds}`);
});

test("probeDuration reports nothing for headers it cannot trust", () => {
  resetDir("music");
  const whole = wav(1);
  const cases = [
    ["garbage.wav", Buffer.from("this is not a wave file at all")],
    ["header-only.wav", whole.subarray(0, 36)],
    ["short.wav", whole.subarray(0, 30)],
    ["empty.mp3", Buffer.alloc(0)],
    ["noise.flac", Buffer.from("fLaC")],
    ["song.ogg", Buffer.from("OggS not really")],
  ];
  for (const [name, contents] of cases) {
    const file = put("music", name, contents);
    assert.equal(probeDuration(file, contents.length), undefined, `${name} must report no duration`);
  }
});

// --- adding ------------------------------------------------------------------

function source(name, contents) {
  const file = path.join(root, name);
  fs.writeFileSync(file, contents);
  return file;
}

test("addMediaFile moves a good file into the library", () => {
  resetDir("music");
  const src = source("upload.mp3", "new audio bytes");
  const result = addMediaFile("music", "New Track.mp3", { path: src, size: 15 });
  assert.equal(result.ok, true);
  assert.equal(result.filename, "New Track.mp3");
  assert.equal(result.replaced, false);
  assert.equal(fs.existsSync(path.join(mediaDir("music"), "New Track.mp3")), true);
  assert.equal(fs.existsSync(src), false, "a successful add moves the temp file rather than copying it");
});

test("addMediaFile rejects an empty file and an oversized one", () => {
  resetDir("music");
  const empty = source("empty.mp3", "");
  const emptyResult = addMediaFile("music", "empty.mp3", { path: empty, size: 0 });
  assert.equal(emptyResult.ok, false);
  assert.equal(emptyResult.status, 400);
  assert.equal(fs.existsSync(path.join(mediaDir("music"), "empty.mp3")), false, "nothing must land in the library");

  // The size guard reads the declared field, not the disk, so this exercises
  // the oversized-rejection path without writing 200 MB to disk.
  const small = source("small.mp3", "abc");
  const hugeResult = addMediaFile("music", "huge.mp3", { path: small, size: MAX_UPLOAD_BYTES + 1 });
  assert.equal(hugeResult.ok, false);
  assert.equal(hugeResult.status, 413, "a file over the cap is refused before any bytes move");
  assert.equal(fs.existsSync(path.join(mediaDir("music"), "huge.mp3")), false);
});

test("addMediaFile rejects an extension that does not belong to the kind", () => {
  resetDir("music");
  const src = source("wrong.bin", "abc");
  const asMusic = addMediaFile("music", "cover.png", { path: src, size: 3 });
  assert.equal(asMusic.ok, false);
  assert.equal(asMusic.status, 415);
  const asPet = addMediaFile("pet", "song.mp3", { path: src, size: 3 });
  assert.equal(asPet.status, 415, "the allowlist is per kind, not global");
  assert.equal(fs.existsSync(src), true, "a rejected add must not consume the temp file");
});

test("addMediaFile replaces an existing name instead of duplicating it", () => {
  resetDir("music");
  put("music", "dup.mp3", "old");
  const src = source("dup-src.mp3", "entirely new");
  const result = addMediaFile("music", "dup.mp3", { path: src, size: 12 });
  assert.equal(result.ok, true);
  assert.equal(result.replaced, true, "the caller and the panel both need to know it was a replacement");
  assert.equal(fs.readFileSync(path.join(mediaDir("music"), "dup.mp3"), "utf8"), "entirely new");
  assert.equal(fs.readdirSync(mediaDir("music")).length, 1, "suffix numbering would create a second entry nobody asked for");
});

test("addMediaFile reduces a path-shaped name to a safe basename", () => {
  resetDir("music");
  const src = source("escape-src.mp3", "abc");
  const result = addMediaFile("music", "../../escape.mp3", { path: src, size: 3 });
  assert.equal(result.ok, true);
  assert.equal(result.filename, "escape.mp3", "the name is reduced before it is ever joined to a directory");
  assert.equal(fs.existsSync(path.join(mediaDir("music"), "escape.mp3")), true);
  assert.equal(fs.existsSync(path.join(root, "escape.mp3")), false, "nothing may be written outside music/");
});

// --- deleting ----------------------------------------------------------------

test("deleteMediaFile removes one file and returns its size", () => {
  resetDir("music");
  put("music", "gone.mp3", "12345");
  assert.equal(deleteMediaFile("music", "gone.mp3"), 5, "the removed byte count is what the panel reports");
  assert.equal(mediaFileExists("music", "gone.mp3"), false);
});

test("deleteMediaFile refuses a traversal name and a missing file", () => {
  resetDir("music");
  assert.throws(() => deleteMediaFile("music", "../prefs.json"), UnsafePathError, "a traversal name is invalid, not a lookup");
  assert.throws(() => deleteMediaFile("music", "nope.mp3"), UnsafePathError, "a missing file is a rejected path too");
});

test("mediaFileExists answers without throwing for hostile names", () => {
  resetDir("music");
  put("music", "here.mp3", "x");
  assert.equal(mediaFileExists("music", "here.mp3"), true);
  assert.equal(mediaFileExists("music", "not-there.mp3"), false);
  assert.equal(mediaFileExists("music", "../here.mp3"), false);
});
